services:
   db:
     image: mongo:latest
     volumes:
       - db_data:/data/db

     restart: always
     ports:
       - "27017:27017"
   jobreferralsystem:
     depends_on:
       - db
     image: jobreferralsystemserver:latest
     ports:
       - "1304:1304"
     restart: always
volumes:
    db_data: {}
